from sqlmodel import SQLModel
from typing import Optional
from datetime import datetime
from enum import Enum


# ---------------------------------------------------
# Application status enum
# Restricts application status to valid values only
# ---------------------------------------------------
class ApplicationStatus(str, Enum):
    APPLIED = "APPLIED"
    SHORTLISTED = "SHORTLISTED"
    INTERVIEW = "INTERVIEW"
    REJECTED = "REJECTED"
    HIRED = "HIRED"


    # ---------------------------------------------------
# Base schema
# Shared fields used across multiple application schemas
# ---------------------------------------------------
class ApplicationBase(SQLModel):
    job_id: int              # Job being applied to
    candidate_id: int        # Candidate who is applying
    resume_id: int           # Resume used for this application



# ---------------------------------------------------
# Create schema (Apply Job)
# Used in: POST /applications
# Client sends only these fields
# ---------------------------------------------------
class ApplicationCreate(ApplicationBase):
    cover_letter: Optional[str] = None   # Optional cover letter text



# ---------------------------------------------------
# Read schema (API Response)
# Used when returning application data to client
# ---------------------------------------------------
class ApplicationRead(ApplicationBase):
    id: int                          # Application ID (generated by DB)
    status: ApplicationStatus        # Current application status
    applied_at: datetime             # When candidate applied


# ---------------------------------------------------
# Status update schema
# Used in: PATCH /applications/{application_id}/status
# Employer updates application status
# ---------------------------------------------------
class ApplicationStatusUpdate(SQLModel):
    status: ApplicationStatus        # Must be a valid enum value


