from sqlmodel import SQLModel
from typing import Optional, List
from datetime import datetime
from enum import Enum


# ---------------------------------------------------
# Candidate experience level enum
# Restricts experience values to valid options
# ---------------------------------------------------
class ExperienceLevel(str, Enum):
    FRESHER = "FRESHER"
    JUNIOR = "JUNIOR"
    MID = "MID"
    SENIOR = "SENIOR"



# ---------------------------------------------------
# Preferred job type enum
# Used for candidate job preferences
# ---------------------------------------------------
class JobType(str, Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERNSHIP = "INTERNSHIP"
    FREELANCE = "FREELANCE"


# ---------------------------------------------------
# Base schema
# Shared fields across candidate schemas
# ---------------------------------------------------
class CandidateBase(SQLModel):
    name: str                          # Candidate full name
    email: str                         # Candidate email address
    skills: List[str]                  # List of skills (e.g. ["Python", "FastAPI"])
    experience_level: ExperienceLevel  # Overall experience level
    preferred_job_type: JobType        # Preferred job type
    preferred_location: Optional[str] = None  # City / Remote preference


# ---------------------------------------------------
# Create schema
# Used in: POST /candidates
# Client sends these fields
# ---------------------------------------------------
class CandidateCreate(CandidateBase):
    pass


# ---------------------------------------------------
# Update schema
# Used in: PUT /candidates/{candidate_id}
# Partial updates allowed
# ---------------------------------------------------
class CandidateUpdate(SQLModel):
    name: Optional[str] = None
    skills: Optional[List[str]] = None
    experience_level: Optional[ExperienceLevel] = None
    preferred_job_type: Optional[JobType] = None
    preferred_location: Optional[str] = None


# ---------------------------------------------------
# Read schema (API Response)
# Returned to client
# ---------------------------------------------------
class CandidateRead(CandidateBase):
    id: int                            # Candidate ID (generated by DB)
    created_at: datetime               # Account creation timestamp


