"""initial migration-2

Revision ID: 7a25571994be
Revises: 8f1382a54bed
Create Date: 2026-01-19 15:39:09.876511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a25571994be'
down_revision: Union[str, Sequence[str], None] = '8f1382a54bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employer', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer', 'location')
    # ### end Alembic commands ###
