"""initial migration-1

Revision ID: 8f1382a54bed
Revises: afb1abf86d6d
Create Date: 2026-01-19 15:24:00.232462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f1382a54bed'
down_revision: Union[str, Sequence[str], None] = 'afb1abf86d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('preferred_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('candidate', 'skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'skills',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('candidate', 'preferred_location')
    # ### end Alembic commands ###
