"""initial migration

Revision ID: afb1abf86d6d
Revises: 
Create Date: 2026-01-19 15:09:29.934243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afb1abf86d6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('experience_level', sa.Enum('FRESHER', 'JUNIOR', 'MID', 'SENIOR', name='experiencelevel'), nullable=False))
    op.add_column('candidate', sa.Column('preferred_job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='jobtype'), nullable=False))
    op.execute(
    """
    ALTER TABLE candidate
    ALTER COLUMN skills
    TYPE JSON
    USING skills::json
    """
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'skills',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidate', 'preferred_job_type')
    op.drop_column('candidate', 'experience_level')
    # ### end Alembic commands ###
