"""initial migration-3

Revision ID: f16b81cc1616
Revises: 7a25571994be
Create Date: 2026-01-19 16:37:36.065963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f16b81cc1616'
down_revision: Union[str, Sequence[str], None] = '7a25571994be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('APPLIED', 'REVIEWING', 'SHORTLISTED', 'REJECTED', 'HIRED', name='applicationstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'status',
               existing_type=sa.Enum('APPLIED', 'REVIEWING', 'SHORTLISTED', 'REJECTED', 'HIRED', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
